name: chromium

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]

    steps:
      - name: Mount workspace to /mnt
        if: runner.os == 'Linux'
        run: |
          sudo mkdir /mnt/work
          sudo mount --bind /mnt/work ${{ github.workspace }}
          sudo chown runner:runner ${{ github.workspace }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gperf
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install python dependencies
        run: python3 -m pip install httplib2

      - name: Checkout Chromium
        run: python3 bootstrap.py --revision 124.0.6315.2

      - name: Build
        run: |
          python3 gn_gen.py
          python3 build.py base
