name: chromium

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Bootstrap
        env:
          EXTRA_GN_ARGS: import("${{ github.workspace }}/vendor/build_tools/third_party/goma.gn")
          SECRET_FILE_CONTENT: ${{ secrets.GOMA_OAUTH2_CONFIG }}
        run: |
          printf "$SECRET_FILE_CONTENT" > ~/.goma_oauth2_config
          ./goma.js
          ./bootstrap.sh

      - name: Clear Space
        run: |
          sudo rm -rf /usr/share/dotnet/ /usr/local/lib/android /var/lib/docker /opt/ghc
          df -h $GITHUB_WORKSPACE

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install gperf
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build
        run: ./build.sh "-j 200 content"
