name: chromium

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clear Space
        run: |
          sudo rm -rf /usr/share/dotnet/ /usr/local/lib/android /var/lib/docker /opt/ghc
          df -h $GITHUB_WORKSPACE

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install gperf
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: '10G'

      - name: Bootstrap
        env:
          EXTRA_GN_ARGS: cc_wrapper="/usr/bin/ccache"
        run: ./bootstrap.sh

      - name: Build
        if: success()
        env:
          CCACHE_SLOPPINESS: time_macros
        run: ./build.sh

      - name: Remove src
        uses: JesseTG/rm@v1.0.3
        with:
          path: src
